### ISSUE TITLE
parse 해결과제

### ISSUE THREAD

**Issue by zoovely** [lamPolar/minishell#29]
- [x] heredoc이 앞에 있는 파일명은 aftertokenize때 환경 변수 value로 안바꿔준다 (따옴표 안이든 밖이든)
- [x] siganl fork 전에 무시시키고, exitcode 업데이트 시켰을 때 다시 설정하는 거 (cat | ls 후 ctrl+C 눌렀을 떄 $?가 0) -> execute_pipe norm check
- [x] export_builtin에서 오름차순 정렬할 떄 leak 나는 부분 찾아서 수정하기

**Comment by zoovely** [comment]
export leak 해결

**Comment by lamPolar** [comment]
- [x] echo hello > $NOT_EXISTS 같은거 했을때 ambiguous redirect 나와야  함.
=> execute파트에서 redirection 체크할 때 에러메세지 추가해줌

아니 이게 뭐야 체크리스트가 되다니

**Comment by zoovely** [comment]
끝~

**Comment by lamPolar** [comment]
```
KINDER🥚 > echo $'a'
a
KINDER🥚 > << $'a'
> $a

bash-3.2$ echo $'a'
a
bash-3.2$ << $'a'
> a
```
 이거 디펜스 가능할까여??

**Comment by zoovely** [comment]
$'a'는 a를 입력해야 꺼지도록 수정했습니다~
