### ISSUE TITLE
export 값 추가시 파싱추가

### ISSUE THREAD

**Issue by lamPolar** [lamPolar/minishell#32]
KINDER🥚 > export LS='ls -l hello | cat < gogo.log'
KINDER🥚 > $LS
KINDER: ls -l hello | cat < gogo.log: command not found
KINDER🥚 > ls -l hello | cat < gogo.log
KINDER: No such file or directory
ls: hello: No such file or directory

bash-3.2$ export LS='ls -l hello | cat < gogo.log'
bash-3.2$ $LS
ls: <: No such file or directory
ls: cat: No such file or directory
ls: gogo.log: No such file or directory
ls: hello: No such file or directory
ls: |: No such file or directory

스페이스바 기준으로 하나하나를 다시 파싱해서 실행시켜야함.
....해..? 말아...?

**Comment by lamPolar** [comment]
export a= '          ls -l '
하면, 저장시에는 공백을 포함해서 저장해야함. -> 이건 됨

echo $a 하면 공백들이 인자 구분자가 되지만
echo “$a” 식으로 따옴표 안에 들어갈 경우에는, 공백이 인자 구분자가 되지 않음.

**Comment by zoovely** [comment]
1. subject가 ’ inhibit all interpretation of a sequence of characters. 이므로 명령어와 옵션 단위로 쪼개지 않아도 될 것이라고 생각함 (절대 귀찮은거 아님)
2. 둘 다 공백인자 포함해서 출력하기로 이미 결정했었음.... 이거 때문에 재배한테 물어봤었는데 재배쉘도 둘 다 공백 포함하여 나옴
