### ISSUE TITLE
heredoc시 시그널 안먹힘

### ISSUE THREAD

**Issue by zoovely** [lamPolar/minishell#36]
cat만 실행 후 문자열 입력하다가 ctrl+C 누르면 멈추는데
<< 사용해서 문자열 입력하는 모든 것에서는 ctrl+C를 눌러도 안멈춤
왜지??? 시그널을 막는 곳은 pipe가 root일때만인데 파이프 없는 line에서도 안먹힘

**Comment by lamPolar** [comment]
해결된것같음 테스트 예정
